=== rsmaior/modelagens/conversao_modelagens/arquivo_mapeamento_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Arquivo Mapeamento",
  "description": "Arquivo que descreve o mapeamento entre especificações",
  "type": "object",
  "definitions": {
    "afixo": {
      "type": "object",
      "properties": {
        "tipo": {
          "type": "string",
          "enum": ["sufixo", "prefixo"]
        },
        "POINT": { "type": "string" },
        "LINESTRING": { "type": "string" },
        "POLYGON": { "type": "string" }
      },
      "required": ["tipo", "POINT", "LINESTRING", "POLYGON"],
      "additionalProperties": false
    },
    "valores": {
      "type": "object",
      "properties": {
        "nome_atributo": { "type": "string" },
        "valor": {
          "type": [
            "string",
            "number",
            "boolean",
            "null"
          ]
        }
      },
      "required": ["nome_atributo", "valor"],
      "additionalProperties": false
    },
    "valores_concatenar": {
      "type": "object",
      "properties": {
        "nome_atributo": { "type": "string" },
        "concatenar": { "type": "boolean" },
        "valor": {
          "type": [
            "string",
            "number",
            "boolean",
            "null"
          ]
        }
      },
      "required": ["nome_atributo", "valor"],
      "additionalProperties": false
    },
    "filtro": {
      "oneOf": [
        { 
          "type": "object",
          "properties": {
            "$or": { 
              "type": "array",
              "items": { "$ref": "#/definitions/filtro" },
              "minItems": 2
            }
          },
          "required": ["$or"],
          "additionalProperties": false
        },
        { 
          "type": "object",
          "properties": {
            "$and": { 
              "type": "array",
              "items": { "$ref": "#/definitions/filtro" },
              "minItems": 2
            }
          },
          "required": ["$and"],
          "additionalProperties": false
        },
        { 
          "type": "object",
          "properties": {
            "$not": { 
              "$ref": "#/definitions/filtro"
            }
          },
          "required": ["$not"],
          "additionalProperties": false
        },
        { 
          "$ref": "#/definitions/valores"
        }
      ]
    },
    "mapeamento_atributo": {
      "type": "object",
      "properties": {
        "__comment": { "type": "string" },
        "attr_ida": { "type": "string" },
        "attr_volta": { "type": "string" },
        "traducao": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "valor_ida": {
                "type": [
                  "string",
                  "number",
                  "boolean",
                  "null"
                ]
              },
              "valor_volta": {
                "type": [
                  "string",
                  "number",
                  "boolean",
                  "null"
                ]
              },
              "sentido": {
                "type": "string",
                "enum": ["ida", "volta"]
              }
            },
            "required": ["valor_ida", "valor_volta"],
            "additionalProperties": false
          },
          "minItems": 1
        }
      },
      "required": ["attr_ida", "attr_volta"],
      "additionalProperties": false
    },
    "mapeamento_classe": {
      "type": "object",
      "properties": {
        "__comment": { "type": "string" },
        "classe_ida": { "type": "string" },
        "classe_volta": { "type": "string" },
        "com_afixo_geom_ida": { "type": "boolean" },
        "com_afixo_geom_volta": { "type": "boolean" },
        "agregar_geom_ida": { "type": "boolean" },
        "agregar_geom_volta": { "type": "boolean" },
        "com_schema_ida": { "type": "boolean" },
        "com_schema_volta": { "type": "boolean" },
        "sentido": {
          "type": "string",
          "enum": ["ida", "volta"]
        },
        "atributos_default_ida": {
          "type": "array",
          "items": { "$ref": "#/definitions/valores" },
          "minItems": 1
        },
        "atributos_default_volta": {
          "type": "array",
          "items": { "$ref": "#/definitions/valores" },
          "minItems": 1
        },
        "mapeamento_atributos": {
          "type": "array",
          "items": { "$ref": "#/definitions/mapeamento_atributo" },
          "minItems": 1
        },
        "filtro_ida": {
          "$ref": "#/definitions/filtro"
        },
        "filtro_volta": {
          "$ref": "#/definitions/filtro"
        },
        "mapeamento_multiplo": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "__comment": {
                "type": "string"
              },
              "tupla_ida": {
                "type": "array",
                "items": { "$ref": "#/definitions/valores_concatenar" },
                "minItems": 1
              },
              "tupla_volta": {
                "type": "array",
                "items": { "$ref": "#/definitions/valores_concatenar" },
                "minItems": 1
              },
              "sentido": {
                "type": "string",
                "enum": ["ida", "volta"]
              }
            },
            "required": ["tupla_ida", "tupla_volta"],
            "additionalProperties": false
          },
          "minItems": 1
        }
      },
      "required": ["classe_ida", "classe_volta"],
      "additionalProperties": false
    }
  },
  "properties": {
    "mapeamento_classes": {
      "type": "array",
      "items": { "$ref": "#/definitions/mapeamento_classe" }
    },
    "mapeamento_atributos": {
      "description": "Mapeamento de atributos aplicado as feições de todas as classes. Segundo mapeamento a ser realizado.",
      "type": "array",
      "items": { "$ref": "#/definitions/mapeamento_atributo" }
    },
    "atributos_default_ida": {
      "description": "Valores default aplicado a todas as classes no mapeamento de ida. Primeiro mapeamento a ser realizado.",
      "type": "array",
      "items": { "$ref": "#/definitions/valores" }
    },
    "atributos_default_volta": {
      "description": "Valores default aplicado a todas as classes no mapeamento de volta. Primeiro mapeamento a ser realizado.",
      "type": "array",
      "items": { "$ref": "#/definitions/valores" }
    },
    "schema_ida": { "type": "string" },
    "schema_volta": { "type": "string" },
    "agregar_geom_ida": { "type": "boolean" },
    "agregar_geom_volta": { "type": "boolean" },
    "afixo_geom_ida": {
      "$ref": "#/definitions/afixo"
    },
    "afixo_geom_volta": {
      "$ref": "#/definitions/afixo"
    },
    "__comment": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": ["mapeamento_classes"]
}

=== rsmaior/modelagens/arquivos_mapeamento/conversao_postgis213_postgis30lite.json
{"__comment":"UTF-8",
    "schema_ida": "cb",
    "schema_volta": "edgv",
    "afixo_geom_ida": {
      "tipo": "sufixo",
      "POINT": "_p",
      "LINESTRING": "_l",
      "POLYGON": "_a"
    },
    "afixo_geom_volta": {
        "tipo": "sufixo",
        "POINT": "_p",
        "LINESTRING": "_l",
        "POLYGON": "_a"
      },
    "agregar_geom_ida": true,
    "agregar_geom_volta": true,
    "mapeamento_classes": [
        {"__comment":"veg_brejo_pantano <-> veg_brejo_pantano",
            "classe_ida":"veg_brejo_pantano",
            "classe_volta":"veg_brejo_pantano",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95}],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },
        {"__comment":"veg_caatinga <-> veg_caatinga",
            "classe_ida":"veg_caatinga",
            "classe_volta":"veg_caatinga",
            "atributos_default_ida":[{"nome_atributo":"secundaria", "valor":95}],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },
        {"__comment":"veg_campinarana <-> veg_campinarana",
            "classe_ida":"veg_campinarana",
            "classe_volta":"veg_campinarana",
            "atributos_default_ida":[{"nome_atributo":"secundaria", "valor":95}],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },
        {"__comment":"veg_campo <-> veg_campo",
            "classe_ida":"veg_campo",
            "classe_volta":"veg_campo",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95},
                {"nome_atributo":"antropizada", "valor":95},
                {"nome_atributo":"classificacaoporte", "valor":95},
                {"nome_atributo":"densidade", "valor":2}
            ],
            "atributos_default_volta":[{"nome_atributo":"ocorrenciaem", "valor":96}]
        },
        {"__comment":"veg_estepe --> veg_campo",
            "classe_ida":"veg_estepe",
            "classe_volta":"veg_campo",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95},
                {"nome_atributo":"antropizada", "valor":95},
                {"nome_atributo":"classificacaoporte", "valor":95},
                {"nome_atributo":"densidade", "valor":2}
            ]
        },
        {"__comment":"veg_macega_chavascal --> veg_campo",
            "classe_ida":"veg_macega_chavascal",
            "classe_volta":"veg_campo",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95},
                {"nome_atributo":"tipocampo", "valor":1},
                {"nome_atributo":"densidade", "valor":2}
            ]
        },
        {"__comment":"veg_cerrado_cerradao <-> veg_cerrado",
            "classe_ida":"veg_cerrado_cerradao",
            "classe_volta":"veg_cerrado",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95},
                {"nome_atributo":"vereda", "valor":9999}
            ],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },
        {"__comment":"veg_floresta <-> veg_floresta",
            "classe_ida":"veg_floresta",
            "classe_volta":"veg_floresta",
            "atributos_default_ida":[{"nome_atributo":"secundaria", "valor":95}],
            "atributos_default_volta":[{"nome_atributo":"caracteristicafloresta", "valor":0}],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },
        {"__comment":"veg_mangue <-> veg_mangue",
            "classe_ida":"veg_mangue",
            "classe_volta":"veg_mangue",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95},
                {"nome_atributo":"tipomanguezal", "valor":95}
            ],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade"}
            ]
        },
        {"__comment":"veg_area_contato <-> veg_area_contato",
            "classe_ida":"veg_area_contato",
            "classe_volta":"veg_area_contato",
            "atributos_default_ida":[
                {"nome_atributo":"secundaria", "valor":95},
                {"nome_atributo":"tipoveg", "valor":95}
            ],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },
        {"__comment":"veg_veg_cultivada <-> veg_veg_cultivada",
            "classe_ida":"veg_veg_cultivada",
            "classe_volta":"veg_veg_cultivada",
            "atributos_default_volta":[{"nome_atributo":"denso", "valor":0}]
        },
        {"__comment":"veg_veg_cultivada <-- veg_reflorestamento",
            "classe_ida":"veg_veg_cultivada",
            "classe_volta":"veg_reflorestamento",
            "sentido": "volta",
            "atributos_default_volta":[{"nome_atributo":"denso", "valor":0}]
        },
        {"__comment":"veg_veg_restinga <-> veg_veg_restinga",
            "classe_ida":"veg_veg_restinga",
            "classe_volta":"veg_veg_restinga",
            "atributos_default_ida":[{"nome_atributo":"secundaria", "valor":95}],
            "mapeamento_atributos":[
                {"attr_ida": "denso","attr_volta": "densidade",
                    "traducao":[{"valor_ida": 0, "valor_volta": 95}]
                }
            ]
        },

        {"__comment":"hid_massa_dagua <-> hid_massa_dagua",
            "classe_ida":"hid_massa_dagua",
            "classe_volta":"hid_massa_dagua",
            "filtro_volta":{"nome_atributo": "possuitrechodrenagem", "valor": 0},
            "atributos_default_ida":[
                {"nome_atributo":"dominialidade", "valor":95},
                {"nome_atributo":"artificial", "valor":95},
                {"nome_atributo":"possuitrechodrenagem", "valor":0}
            ],
            "mapeamento_atributos":[
                {"attr_ida": "salinidade","attr_volta": "salgada",
                    "traducao":[
                        {"valor_ida": 0, "valor_volta": 95},
                        {"valor_ida": 1, "valor_volta": 0},
                        {"valor_ida": 2, "valor_volta": 1}
                    ]
                }
            ]
        },
        {"__comment":"hid_trecho_massa_dagua <-> hid_massa_dagua",
            "classe_ida":"hid_trecho_massa_dagua",
            "classe_volta":"hid_massa_dagua",
            "filtro_ida":{
                "$not":{"nome_atributo": "tipotrechomassa", "valor": 2}
            },
            "filtro_volta":{"nome_atributo": "possuitrechodrenagem", "valor": 1},
            "atributos_default_ida":[
                {"nome_atributo":"dominialidade", "valor":95},
                {"nome_atributo":"artificial", "valor":95},
                {"nome_atributo":"possuitrechodrenagem", "valor":1}
            ],
            "mapeamento_atributos":[
                {"attr_ida": "tipotrechomassa","attr_volta": "tipomassadagua"},
                {"attr_ida": "salinidade","attr_volta": "salgada",
                    "traducao":[
                        {"valor_ida": 0, "valor_volta": 95},
                        {"valor_ida": 1, "valor_volta": 0},
                        {"valor_ida": 2, "valor_volta": 1}
                    ]
                }
            ]
        },
        {"__comment":"hid_trecho_massa_dagua <-> hid_canal",
            "classe_ida":"hid_trecho_massa_dagua",
            "classe_volta":"hid_canal",
            "filtro_ida":{"nome_atributo": "tipotrechomassa", "valor": 2},
            "atributos_default_ida":[
                {"nome_atributo":"finalidade", "valor":9999},
                {"nome_atributo":"geometriaaproximada", "valor":0},
                {"nome_atributo":"matconstr", "valor":9999},
                {"nome_atributo":"operacional", "valor":1},
                {"nome_atributo":"situacaofisica", "valor":7},
                {"nome_atributo":"tipoalterantrop", "valor":30},
                {"nome_atributo":"usoprincipal", "valor":9999}
            ],
            "atributos_default_volta":[
                {"nome_atributo":"tipotrechomassa", "valor":2},
                {"nome_atributo":"regime", "valor":1},
                {"nome_atributo":"salinidade", "valor":0}
            ]
        },
        {"__comment":"hid_bacia_hidrografica --> hid_massa_dagua",
            "classe_ida":"hid_bacia_hidrografica",
            "classe_volta":"hid_massa_dagua",
            "sentido":"ida",
            "atributos_default_ida":[
                {"nome_atributo":"dominialidade", "valor":95},
                {"nome_atributo":"artificial", "valor":0},
                {"nome_atributo":"possuitrechodrenagem", "valor":9999},
                {"nome_atributo":"regime", "valor":9999},
                {"nome_atributo":"salgada", "valor":9999},
                {"nome_atributo":"tipomassadagua", "valor":99}
            ]
        },
        {"__comment":"hid_barragem <-> hid_barragem",
            "classe_ida":"hid_barragem",
            "classe_volta":"hid_barragem",
            "atributos_default_ida":[
                {"nome_atributo":"dominialidade", "valor":95},
                {"nome_atributo":"artificial", "valor":95},
